# Generated by Django 4.0.3 on 2022-03-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('genre', models.CharField(max_length=128)),
                ('publisher', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('date_release', models.DateField()),
                ('translation_by', models.CharField(blank=True, max_length=128)),
                ('description', models.TextField()),
            ],
        ),
    ]
